version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lotus-postgres
    environment:
      POSTGRES_DB: lotus_checkin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lotus-network

  redis:
    image: redis:7-alpine
    container_name: lotus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lotus-network
    command: redis-server --appendonly yes

networks:
  lotus-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 